category: application
doc: |
  Application definition for a configuration file of the paraprobe-selector tool.
  
  This tool is part of the paraprobe-toolbox. Inspect :ref:`NXapm_paraprobe_tool_config` for details.
symbols:
  doc: |
    The symbols used in the schema to specify e.g. dimensions of arrays.
type: group
NXapm_paraprobe_selector_config(NXobject):
  (NXentry):
    exists: ['min', '1', 'max', '1']
    definition(NX_CHAR):
      \@version(NX_CHAR):
      enumeration: [NXapm_paraprobe_selector_config]
    select(NXapm_paraprobe_tool_config):
      exists: ['min', '1', 'max', '1']
      (NXidentifier):
        exists: optional
      analysis_identifier(NX_UINT):
        exists: recommended
      reconstruction(NXserialized):
        type(NX_CHAR):
        path(NX_CHAR):
        checksum(NX_CHAR):
        algorithm(NX_CHAR):
        position(NX_CHAR):
        mass_to_charge(NX_CHAR):
      ranging(NXserialized):
        type(NX_CHAR):
        path(NX_CHAR):
        checksum(NX_CHAR):
        algorithm(NX_CHAR):
        ranging_definitions(NX_CHAR):
      
      # filter that represent here also the tool-specific config
      spatial_filter(NXspatial_filter):
        windowing_method(NX_CHAR):
        hexahedron_set(NXcg_hexahedron_set):
          exists: optional
          dimensionality(NX_POSINT):
          cardinality(NX_POSINT):
          identifier_offset(NX_INT):
          hexahedra(NXcg_face_list_data_structure):
            vertices(NX_UINT):
        cylinder_set(NXcg_cylinder_set):
          exists: optional
          dimensionality(NX_POSINT):
          cardinality(NX_POSINT):
          identifier_offset(NX_INT):
          center(NX_NUMBER):
          height(NX_NUMBER):
          radii(NX_NUMBER):
        ellipsoid_set(NXcg_ellipsoid_set):
          exists: optional
          dimensionality(NX_POSINT):
          cardinality(NX_POSINT):
          identifier_offset(NX_INT):
          center(NX_NUMBER):
          half_axes_radii(NX_NUMBER):
          orientation(NX_NUMBER):
        polyhedron_set(NXcg_polyhedron_set):
          exists: optional
        
        # TODO
        bitmask(NXcs_filter_boolean_mask):
          exists: optional
          number_of_objects(NX_UINT):
          bitdepth(NX_UINT):
          mask(NX_UINT):
          
          # leave open if scalar or matrix
          # dim: (i,)
          identifier(NX_UINT):
      evaporation_id_filter(NXsubsampling_filter):
        exists: optional
        min_incr_max(NX_INT):
      iontype_filter(NXmatch_filter):
        exists: optional
        method(NX_CHAR):
        match(NX_NUMBER):
      hit_multiplicity_filter(NXmatch_filter):
        exists: optional
        method(NX_CHAR):
        match(NX_NUMBER):
    common(NXapm_paraprobe_tool_common):
      status(NX_CHAR):
      programID(NXprogram):
        exists: ['min', '1', 'max', 'unbounded']
        program(NX_CHAR):
          \@version(NX_CHAR):
      profiling(NXcs_profiling):
        exists: recommended
        start_time(NX_DATE_TIME):
        end_time(NX_DATE_TIME):
        total_elapsed_time(NX_FLOAT):
        current_working_directory(NX_CHAR):

# ++++++++++++++++++++++++++++++++++ SHA HASH ++++++++++++++++++++++++++++++++++
# 5a17706d0001eebfd0c4d22660da487ae1db5719a721edb0ad2b3242c014ecc1
# <?xml version='1.0' encoding='UTF-8'?>
# <?xml-stylesheet type="text/xsl" href="nxdlformat.xsl"?>
# <!--
# # NeXus - Neutron and X-ray Common Data Format
# #
# # Copyright (C) 2024-2025 NeXus International Advisory Committee (NIAC)
# #
# # This library is free software; you can redistribute it and/or
# # modify it under the terms of the GNU Lesser General Public
# # License as published by the Free Software Foundation; either
# # version 3 of the License, or (at your option) any later version.
# #
# # This library is distributed in the hope that it will be useful,
# # but WITHOUT ANY WARRANTY; without even the implied warranty of
# # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# # Lesser General Public License for more details.
# #
# # You should have received a copy of the GNU Lesser General Public
# # License along with this library; if not, write to the Free Software
# # Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
# #
# # For further information, see http://www.nexusformat.org
# -->
# <definition xmlns="http://definition.nexusformat.org/nxdl/3.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" category="application" type="group" name="NXapm_paraprobe_selector_config" extends="NXobject" xsi:schemaLocation="http://definition.nexusformat.org/nxdl/3.1 ../nxdl.xsd">
#     <symbols>
#         <doc>
#              The symbols used in the schema to specify e.g. dimensions of arrays.
#         </doc>
#     </symbols>
#     <doc>
#          Application definition for a configuration file of the paraprobe-selector tool.
#          
#          This tool is part of the paraprobe-toolbox. Inspect :ref:`NXapm_paraprobe_tool_config` for details.
#     </doc>
#     <group type="NXentry" minOccurs="1" maxOccurs="1">
#         <field name="definition" type="NX_CHAR">
#             <attribute name="version" type="NX_CHAR"/>
#             <enumeration>
#                 <item value="NXapm_paraprobe_selector_config"/>
#             </enumeration>
#         </field>
#         <group name="select" type="NXapm_paraprobe_tool_config" minOccurs="1" maxOccurs="1">
#             <group type="NXidentifier" optional="true"/>
#             <field name="analysis_identifier" type="NX_UINT" recommended="true"/>
#             <group name="reconstruction" type="NXserialized">
#                 <field name="type" type="NX_CHAR"/>
#                 <field name="path" type="NX_CHAR"/>
#                 <field name="checksum" type="NX_CHAR"/>
#                 <field name="algorithm" type="NX_CHAR"/>
#                 <field name="position" type="NX_CHAR"/>
#                 <field name="mass_to_charge" type="NX_CHAR"/>
#             </group>
#             <group name="ranging" type="NXserialized">
#                 <field name="type" type="NX_CHAR"/>
#                 <field name="path" type="NX_CHAR"/>
#                 <field name="checksum" type="NX_CHAR"/>
#                 <field name="algorithm" type="NX_CHAR"/>
#                 <field name="ranging_definitions" type="NX_CHAR"/>
#             </group>
#             <!--filter that represent here also the tool-specific config-->
#             <group name="spatial_filter" type="NXspatial_filter">
#                 <field name="windowing_method" type="NX_CHAR"/>
#                 <group name="hexahedron_set" type="NXcg_hexahedron_set" optional="true">
#                     <field name="dimensionality" type="NX_POSINT"/>
#                     <field name="cardinality" type="NX_POSINT"/>
#                     <field name="identifier_offset" type="NX_INT"/>
#                     <group name="hexahedra" type="NXcg_face_list_data_structure">
#                         <field name="vertices" type="NX_UINT"/>
#                     </group>
#                 </group>
#                 <group name="cylinder_set" type="NXcg_cylinder_set" optional="true">
#                     <field name="dimensionality" type="NX_POSINT"/>
#                     <field name="cardinality" type="NX_POSINT"/>
#                     <field name="identifier_offset" type="NX_INT"/>
#                     <field name="center" type="NX_NUMBER"/>
#                     <field name="height" type="NX_NUMBER"/>
#                     <field name="radii" type="NX_NUMBER"/>
#                 </group>
#                 <group name="ellipsoid_set" type="NXcg_ellipsoid_set" optional="true">
#                     <field name="dimensionality" type="NX_POSINT"/>
#                     <field name="cardinality" type="NX_POSINT"/>
#                     <field name="identifier_offset" type="NX_INT"/>
#                     <field name="center" type="NX_NUMBER"/>
#                     <field name="half_axes_radii" type="NX_NUMBER"/>
#                     <field name="orientation" type="NX_NUMBER"/>
#                 </group>
#                 <group name="polyhedron_set" type="NXcg_polyhedron_set" optional="true"/>
#                 <!--TODO-->
#                 <group name="bitmask" type="NXcs_filter_boolean_mask" optional="true">
#                     <field name="number_of_objects" type="NX_UINT"/>
#                     <field name="bitdepth" type="NX_UINT"/>
#                     <field name="mask" type="NX_UINT"/>
#                     <!--leave open if scalar or matrix
#   dim: (i,)-->
#                     <field name="identifier" type="NX_UINT"/>
#                 </group>
#             </group>
#             <group name="evaporation_id_filter" type="NXsubsampling_filter" optional="true">
#                 <field name="min_incr_max" type="NX_INT"/>
#             </group>
#             <group name="iontype_filter" type="NXmatch_filter" optional="true">
#                 <field name="method" type="NX_CHAR"/>
#                 <field name="match" type="NX_NUMBER"/>
#             </group>
#             <group name="hit_multiplicity_filter" type="NXmatch_filter" optional="true">
#                 <field name="method" type="NX_CHAR"/>
#                 <field name="match" type="NX_NUMBER"/>
#             </group>
#         </group>
#         <group name="common" type="NXapm_paraprobe_tool_common">
#             <field name="status" type="NX_CHAR"/>
#             <group name="programID" type="NXprogram" minOccurs="1" maxOccurs="unbounded">
#                 <field name="program" type="NX_CHAR">
#                     <attribute name="version" type="NX_CHAR"/>
#                 </field>
#             </group>
#             <group name="profiling" type="NXcs_profiling" recommended="true">
#                 <field name="start_time" type="NX_DATE_TIME"/>
#                 <field name="end_time" type="NX_DATE_TIME"/>
#                 <field name="total_elapsed_time" type="NX_FLOAT"/>
#                 <field name="current_working_directory" type="NX_CHAR"/>
#             </group>
#         </group>
#     </group>
# </definition>
