category: application
doc: |
  Application definition for the configuration of the legacy (micro)structure generator
  developed by the Institut für Metallkunde und Metallphysik at RWTH Aachen University.
  
  * `N. Leuning et al. <https://doi.org/10.3390/ma14216588>`_
  * `C. Mießen <https://doi.org/10.18154/RWTH-2017-10148>`_
  * `M. Kühbach <https://doi.org/10.18154/RWTH-2018-00294>`_
  * `M. Kühbach et al. <https://github.com/mkuehbach/GraGLeS>`_
  
  The tool can be used to instantiate specific configurations for two- and three-dimensional discretized microstructures.
  Specifically, single-phase material that is composed of crystals, so-called (parent) grains which are tessellated into so-called sub-grains.
  Grains are modelled as elongated crystals to mimic fundamental geometrical constraints of the interface network in deformed material.
symbols:
  n_categories: |
    How many texture components are distinguished, minimum is 1.
  n_components: |
    How many special texture components are distinguished if any.
  n_ori: |
    Number of discrete orientations that are distributed across the grains.
type: group
NXmicrostructure_imm_config(NXobject):
  (NXentry):
    definition(NX_CHAR):
      enumeration: [NXmicrostructure_imm_config]
    roi(NXobject):
      doc: |
        The computational domain will be synthesized either as a square (for dimensionality = 2)
        or a cube (for dimensionality = 3) with axis-aligned cuboidal parent grains. The domain is
        discretized into material points using either square pixel or cubic voxel as the tessellating
        unit cells.
      dimensionality(NX_UINT):
        doc: |
          Two-dimensional or three-dimensional simulation.
        enumeration: [2, 3]
      discretization(NX_UINT):  # <NumberOfPointsPerSubGrain>15</NumberOfPointsPerSubGrains># simulation ID via command line <SimulationID>10</SimulationID>
        doc: |
          Target value for the number of material points per equivalent
          discrete diameter of the arithmetic average sub-grain.
        unit: NX_UNITLESS
      crystal_symmetry(NX_CHAR):
        doc: |
          Assumed space group of the material.
        enumeration: [fcc, bcc, hcp]
        # <AdditionalFilename>PreferenceOrientations.txt</AdditionalFilename>
        # <CrystalStructure>1</CrystalStructure> # 0, E_HCP, 1 E_FCC, 2 E_BCC, 3 E_DEFAULT_STRUCTURE
      number_of_grains(NX_UINT):  # <NumberOfGrains>8</NumberOfGrains>
        doc: |
          Target value for the number of grains. The actual domain size and grid will be configured
          based on the choices for discretization, number_of_grains, and shape of these grains.
        unit: NX_UNITLESS
      number_of_subgrains(NX_UINT):  # <NumberOfSubgrains>1000</NumberOfSubgrains>
        doc: |
          Target value for the average number of sub-grains per grain.
        unit: NX_UNITLESS
      # <MicroGenMode>0</MicroGenMode> is there another one if not remove
      # <TextureGEN>1</TextureGEN> always one 
      # <!--<UseOrientationSpace>1</UseOrientationSpace>-->
      # <GrainShape>1</GrainShape>
      grain_shape(NX_FLOAT):
        exists: optional
        doc: |
          If available used to define the sequence of relative extent of grains along the y (first value)
          and z-axis (second value) assuming the relative shape along the x-axis is 1. If not provided,
          the relative extent of the grains will be 1 one average along each axis (globulitic structure).
        unit: NX_DIMENSIONLESS
        dim: (2,)
      # <!-- USAGE: 0, E_GLOBULITIC, 1, E_FLAT
      # <DefGrainRelDimensionY>0.05</DefGrainRelDimensionY>
      # <DefGrainRelDimensionZ>1.0</DefGrainRelDimensionZ>
      # remove 0 all the time <RandomnessX>0.00</RandomnessX>
      # remove 0 all the time <RandomnessY>0.00</RandomnessY>
      # <!-- in the case of MicroGenMode 0 (E_VORONOI) this sets dimensions of the average 0.1/0.2cdeformed grain relative to its dimensions in x which is 1.0, randomness controls how the seed points are misplaced -->

    component_analysis(NXobject):
      exists: optional
      doc: |
        In texture research component analyses set on the idea that properties
        of grains different based on orientation with certain regions in orientation
        space show similar trends like a different average dislocation density
        or orientation_spread.
      component_name(NX_CHAR):
        doc: |
          The first entry is always the null model None which measn that an orientation
          is not categorized as a special component. Examples for special components are
          Dillamore, Copper, Cube, Y, P and Q.
        dim: (n_categories,)
      bunge_euler(NX_FLOAT):
        doc: |
          Bunge-Euler angle parameterization of the texture components
          location in orientation space for which specifically different settings
          should be configured.
        unit: NX_ANGLE
        dim: (n_components, 3)
      theta(NX_FLOAT):
        doc: |
          Disorientation angle below which an orientation is categorized as one of the components.
        unit: NX_ANGLE
        dim: (n_components,)
    dislocation_distribution(NXobject):
      doc: |
        Dislocations are modelled as Rayleigh-distributed mean-field density that
        can differ between but is constant within grains and sub-grains.
      min_max_grain(NX_FLOAT):
          doc: |
            The minimum and the maximum dislocation density to distribute across grains.
          unit: NX_ANY  # 1/m^2
          dim: (n_categories, 2)
      min_max_subgrain(NX_FLOAT):
        doc: |
          The minimum and the maximum dislocation density to distribute across sub-grains.
        unit: NX_ANY  # 1/m^2
        dim: (n_categories, 2)
        # <StoredElasticEnergyMax>10.8e14</StoredElasticEnergyMax># <StoredElasticEnergyMin>10.8e14</StoredElasticEnergyMi
      variance_grain(NX_FLOAT):  # <StoredElasticScatterGrain>4.0e14</StoredElasticScatterGrain>
      # <!-- truncating to lower values at 1.0e12-->
        doc: |
          The variance of the dislocation density distribution across the grains.
        unit: NX_ANY  # 1/m^2
        dim: (n_categories,)
      variance_subgrain(NX_FLOAT):  # <StoredElasticScatterSubgrain>0.8e14</StoredElasticScatter>
        doc: |
          The variance of the dislocation density distribution across the sub-grains.
        unit: NX_ANY  # 1/m^2
        dim: (n_categories,)
    orientation_distribution(NXprocess):  # <ReadFromFilename>CR70FeSi.Rogge.MTEX.vpsc.odf.5000.txt</ReadFromFilename>
      doc: |
        Orientations of the grains are sampled from a set of Bunge-Euler angle triplets.
        Orientations of the sub-grains are sampled by scattering the orientation
        of the (parent) grain and with optional Rayleigh-distributed scatter.
      bunge_euler(NX_FLOAT):
        doc: |
          Bunge-Euler angle parameterization of the texture components
          location in orientation space for which specifically different settings
          should be configured.
        unit: NX_ANGLE
        dim: (n_ori, 3)
      variance_subgrain(NX_FLOAT):  # <SubgrainOriScatter>5.0</SubgrainOriScatter>
        doc: |
          The variance of the disorientation of the sub-grain to their parent grain.
        unit: NX_ANGLE
        dim: (n_categories,)
      # what is with preference orientations?
# <ExecuteInParallel>1</ExecuteInParallel> # via OpenMP
# <PlotIPF2DSection>1</PlotIPF2DSection>
# <PlotWindowXMin>0.00</PlotWindowXMin>
# <PlotWindowXMax>1.00</PlotWindowXMax>
# <PlotWindowYMin>0.00</PlotWindowYMin>
# <PlotWindowYMax>1.00</PlotWindowYMax>
# <!--IPF plotting renders a plane-parallel section in the NXNY coordinates
