category: base
doc: |
  Base class to store the configuration when using the MTex/Matlab software.
  
  MTex is a Matlab package for texture analysis used in the Materials and Earth Sciences.
  See `R. Hielscher et al. <https://mtex-toolbox.github.io/publications>`_ and
  the `MTex source code <https://github.com/mtex-toolbox>`_ for details.
type: group
NXms_mtex_config(NXobject):
  conventions(NXcollection):
    doc: |
      Reference frame and orientation conventions.
      Consult the `MTex docs <https://mtex-toolbox.github.io/EBSDReferenceFrame.html>`_ for details.
    x_axis_direction(NX_CHAR):
      doc: |
        TODO with MTex developers
    
    # enumeration:
    # check against v5.12
    z_axis_direction(NX_CHAR):
      doc: |
        TODO with MTex developers
    
    # enumeration:
    a_axis_direction(NX_CHAR):
      doc: |
        TODO with MTex developers
    
    # enumeration:
    b_axis_direction(NX_CHAR):
      doc: |
        TODO with MTex developers
    
    # enumeration:
    euler_angle(NX_CHAR):
      doc: |
        TODO with MTex developers
      enumeration: [unknown, undefined, bunge]
  plotting(NXcollection):
    doc: |
      Settings relevant for generating plots.
    font_size(NX_NUMBER):
      unit: NX_ANY
      doc: |
        TODO with MTex developers
    inner_plot_spacing(NX_NUMBER):
      unit: NX_ANY
      doc: |
        TODO with MTex developers
    outer_plot_spacing(NX_NUMBER):
      unit: NX_ANY
      doc: |
        TODO with MTex developers
    marker_size(NX_NUMBER):
      unit: NX_ANY
      doc: |
        TODO with MTex developers
    figure_size(NX_NUMBER):
      doc: |
        TODO with MTex developers
    show_micron_bar(NX_BOOLEAN):
      doc: |
        True if MTex renders a scale bar with figures.
    show_coordinates(NX_BOOLEAN):
      doc: |
        True if MTex renders a grid with figures.
    pf_anno_fun_hdl:
      doc: |
        Code for the function handle used for annotating pole figure plots.
    color_map(NX_NUMBER):
      unit: NX_UNITLESS
      doc: |
        TODO with MTex developers
      dimensions:
        rank: 2
        dim: [[1, i], [2, 3]]
    default_color_map(NX_NUMBER):
      unit: NX_UNITLESS
      doc: |
        TODO with MTex developers
      dimensions:
        rank: 2
        dim: [[1, i], [2, 3]]
    
    # phase_color_order:
    # doc: |
    # TODO with MTex developers
    # unit: NX_UNITLESS
    # dim: (i,)
    color_palette(NX_CHAR):
    degree_char(NX_CHAR):
      doc: |
        TODO with MTex developers
    arrow_char(NX_CHAR):
      doc: |
        TODO with MTex developers
    marker(NX_CHAR):
      doc: |
        TODO with MTex developers
    marker_edge_color(NX_CHAR):
      doc: |
        TODO with MTex developers
    marker_face_color(NX_CHAR):
      doc: |
        TODO with MTex developers
    hit_test(NX_BOOLEAN):
      doc: |
        TODO with MTex developers
  miscellaneous(NXcollection):
    doc: |
      Miscellaneous other settings of MTex.
    mosek(NX_BOOLEAN):
      doc: |
        TODO with MTex developers
    generating_help_mode(NX_BOOLEAN):
      doc: |
        TODO with MTex developers
    methods_advise(NX_BOOLEAN):
      doc: |
        TODO with MTex developers
    stop_on_symmetry_mismatch(NX_BOOLEAN):
      doc: |
        TODO with MTex developers
    inside_poly(NX_BOOLEAN):
      doc: |
        TODO with MTex developers
    text_interpreter:
  numerics(NXcollection):
    doc: |
      Miscellaneous settings relevant for numerics.
    eps(NX_NUMBER):
      unit: NX_UNITLESS
      doc: |
        Return value of the Matlab eps command.
    fft_accuracy(NX_NUMBER):
      unit: NX_ANY
      doc: |
        TODO with MTex developers
    max_stwo_bandwidth(NX_NUMBER):
      unit: NX_ANY
      doc: |
        TODO with MTex developers
    max_sothree_bandwidth(NX_NUMBER):
      unit: NX_ANY
      doc: |
        TODO with MTex developers
  system(NXcollection):
    doc: |
      Miscellaneous settings relevant of the system where MTex runs.
    memory(NX_NUMBER):
      doc: |
        TODO with MTex developers
    open_gl_bug(NX_BOOLEAN):
      doc: |
        TODO with MTex developers
    save_to_file(NX_BOOLEAN):
      doc: |
        TODO with MTex developers
  path(NXcollection):
    doc: |
      Collection of paths from where MTex reads information and code.
    mtex(NX_CHAR):
      doc: |
        Absolute path to specific component of MTex source code.
    data(NX_CHAR):
      doc: |
        Absolute path to specific component of MTex source code.
    cif(NX_CHAR):
      doc: |
        Absolute path to specific component of MTex source code.
    ebsd(NX_CHAR):
      doc: |
        Absolute path to specific component of MTex source code.
    pf(NX_CHAR):
      doc: |
        Absolute path to specific component of MTex source code.
    odf(NX_CHAR):
      doc: |
        Absolute path to specific component of MTex source code.
    tensor(NX_CHAR):
      doc: |
        Absolute path to specific component of MTex source code.
    example(NX_CHAR):
      doc: |
        Absolute path to specific component of MTex source code.
    import_wizard(NX_CHAR):
      doc: |
        Absolute path to specific component of MTex source code.
    pf_extensions(NX_CHAR):
      doc: |
        List of file type suffixes for which MTex assumes
        texture/pole figure information.
    ebsd_extensions(NX_CHAR):
      doc: |
        List of file type suffixes for which MTex assumes EBSD content.
  
  # version as an instance of (NXprogram) one for MTex one for Matlab

# ++++++++++++++++++++++++++++++++++ SHA HASH ++++++++++++++++++++++++++++++++++
# 0d474bad0811b1d069629c2c635000f8a9e7db15163958fb24d51222d405f3cd
# <?xml version='1.0' encoding='UTF-8'?>
# <?xml-stylesheet type="text/xsl" href="nxdlformat.xsl"?>
# <!--
# # NeXus - Neutron and X-ray Common Data Format
# #
# # Copyright (C) 2014-2024 NeXus International Advisory Committee (NIAC)
# #
# # This library is free software; you can redistribute it and/or
# # modify it under the terms of the GNU Lesser General Public
# # License as published by the Free Software Foundation; either
# # version 3 of the License, or (at your option) any later version.
# #
# # This library is distributed in the hope that it will be useful,
# # but WITHOUT ANY WARRANTY; without even the implied warranty of
# # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# # Lesser General Public License for more details.
# #
# # You should have received a copy of the GNU Lesser General Public
# # License along with this library; if not, write to the Free Software
# # Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
# #
# # For further information, see http://www.nexusformat.org
# -->
# <definition xmlns="http://definition.nexusformat.org/nxdl/3.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" category="base" type="group" name="NXms_mtex_config" extends="NXobject" xsi:schemaLocation="http://definition.nexusformat.org/nxdl/3.1 ../nxdl.xsd">
#     <doc>
#          Base class to store the configuration when using the MTex/Matlab software.
#          
#          MTex is a Matlab package for texture analysis used in the Materials and Earth Sciences.
#          See `R. Hielscher et al. &lt;https://mtex-toolbox.github.io/publications&gt;`_ and
#          the `MTex source code &lt;https://github.com/mtex-toolbox&gt;`_ for details.
#     </doc>
#     <group name="conventions" type="NXcollection">
#         <doc>
#              Reference frame and orientation conventions.
#              Consult the `MTex docs &lt;https://mtex-toolbox.github.io/EBSDReferenceFrame.html&gt;`_ for details.
#         </doc>
#         <field name="x_axis_direction" type="NX_CHAR">
#             <doc>
#                  TODO with MTex developers
#             </doc>
#         </field>
#         <!--enumeration:
# check against v5.12-->
#         <field name="z_axis_direction" type="NX_CHAR">
#             <doc>
#                  TODO with MTex developers
#             </doc>
#         </field>
#         <!--enumeration:-->
#         <field name="a_axis_direction" type="NX_CHAR">
#             <doc>
#                  TODO with MTex developers
#             </doc>
#         </field>
#         <!--enumeration:-->
#         <field name="b_axis_direction" type="NX_CHAR">
#             <doc>
#                  TODO with MTex developers
#             </doc>
#         </field>
#         <!--enumeration:-->
#         <field name="euler_angle" type="NX_CHAR">
#             <doc>
#                  TODO with MTex developers
#             </doc>
#             <enumeration>
#                 <item value="unknown"/>
#                 <item value="undefined"/>
#                 <item value="bunge"/>
#             </enumeration>
#         </field>
#     </group>
#     <group name="plotting" type="NXcollection">
#         <doc>
#              Settings relevant for generating plots.
#         </doc>
#         <field name="font_size" type="NX_NUMBER" units="NX_ANY">
#             <doc>
#                  TODO with MTex developers
#             </doc>
#         </field>
#         <field name="inner_plot_spacing" type="NX_NUMBER" units="NX_ANY">
#             <doc>
#                  TODO with MTex developers
#             </doc>
#         </field>
#         <field name="outer_plot_spacing" type="NX_NUMBER" units="NX_ANY">
#             <doc>
#                  TODO with MTex developers
#             </doc>
#         </field>
#         <field name="marker_size" type="NX_NUMBER" units="NX_ANY">
#             <doc>
#                  TODO with MTex developers
#             </doc>
#         </field>
#         <field name="figure_size" type="NX_NUMBER">
#             <doc>
#                  TODO with MTex developers
#             </doc>
#         </field>
#         <field name="show_micron_bar" type="NX_BOOLEAN">
#             <doc>
#                  True if MTex renders a scale bar with figures.
#             </doc>
#         </field>
#         <field name="show_coordinates" type="NX_BOOLEAN">
#             <doc>
#                  True if MTex renders a grid with figures.
#             </doc>
#         </field>
#         <field name="pf_anno_fun_hdl">
#             <doc>
#                  Code for the function handle used for annotating pole figure plots.
#             </doc>
#         </field>
#         <field name="color_map" type="NX_NUMBER" units="NX_UNITLESS">
#             <doc>
#                  TODO with MTex developers
#             </doc>
#             <dimensions rank="2">
#                 <dim index="1" value="i"/>
#                 <dim index="2" value="3"/>
#             </dimensions>
#         </field>
#         <field name="default_color_map" type="NX_NUMBER" units="NX_UNITLESS">
#             <doc>
#                  TODO with MTex developers
#             </doc>
#             <dimensions rank="2">
#                 <dim index="1" value="i"/>
#                 <dim index="2" value="3"/>
#             </dimensions>
#         </field>
#         <!--phase_color_order:
#   doc: |
#     TODO with MTex developers
#   unit: NX_UNITLESS
#   dim: (i,)-->
#         <field name="color_palette" type="NX_CHAR"/>
#         <field name="degree_char" type="NX_CHAR">
#             <doc>
#                  TODO with MTex developers
#             </doc>
#         </field>
#         <field name="arrow_char" type="NX_CHAR">
#             <doc>
#                  TODO with MTex developers
#             </doc>
#         </field>
#         <field name="marker" type="NX_CHAR">
#             <doc>
#                  TODO with MTex developers
#             </doc>
#         </field>
#         <field name="marker_edge_color" type="NX_CHAR">
#             <doc>
#                  TODO with MTex developers
#             </doc>
#         </field>
#         <field name="marker_face_color" type="NX_CHAR">
#             <doc>
#                  TODO with MTex developers
#             </doc>
#         </field>
#         <field name="hit_test" type="NX_BOOLEAN">
#             <doc>
#                  TODO with MTex developers
#             </doc>
#         </field>
#     </group>
#     <group name="miscellaneous" type="NXcollection">
#         <doc>
#              Miscellaneous other settings of MTex.
#         </doc>
#         <field name="mosek" type="NX_BOOLEAN">
#             <doc>
#                  TODO with MTex developers
#             </doc>
#         </field>
#         <field name="generating_help_mode" type="NX_BOOLEAN">
#             <doc>
#                  TODO with MTex developers
#             </doc>
#         </field>
#         <field name="methods_advise" type="NX_BOOLEAN">
#             <doc>
#                  TODO with MTex developers
#             </doc>
#         </field>
#         <field name="stop_on_symmetry_mismatch" type="NX_BOOLEAN">
#             <doc>
#                  TODO with MTex developers
#             </doc>
#         </field>
#         <field name="inside_poly" type="NX_BOOLEAN">
#             <doc>
#                  TODO with MTex developers
#             </doc>
#         </field>
#         <field name="text_interpreter"/>
#     </group>
#     <group name="numerics" type="NXcollection">
#         <doc>
#              Miscellaneous settings relevant for numerics.
#         </doc>
#         <field name="eps" type="NX_NUMBER" units="NX_UNITLESS">
#             <doc>
#                  Return value of the Matlab eps command.
#             </doc>
#         </field>
#         <field name="fft_accuracy" type="NX_NUMBER" units="NX_ANY">
#             <doc>
#                  TODO with MTex developers
#             </doc>
#         </field>
#         <field name="max_stwo_bandwidth" type="NX_NUMBER" units="NX_ANY">
#             <doc>
#                  TODO with MTex developers
#             </doc>
#         </field>
#         <field name="max_sothree_bandwidth" type="NX_NUMBER" units="NX_ANY">
#             <doc>
#                  TODO with MTex developers
#             </doc>
#         </field>
#     </group>
#     <group name="system" type="NXcollection">
#         <doc>
#              Miscellaneous settings relevant of the system where MTex runs.
#         </doc>
#         <field name="memory" type="NX_NUMBER">
#             <doc>
#                  TODO with MTex developers
#             </doc>
#         </field>
#         <field name="open_gl_bug" type="NX_BOOLEAN">
#             <doc>
#                  TODO with MTex developers
#             </doc>
#         </field>
#         <field name="save_to_file" type="NX_BOOLEAN">
#             <doc>
#                  TODO with MTex developers
#             </doc>
#         </field>
#     </group>
#     <group name="path" type="NXcollection">
#         <doc>
#              Collection of paths from where MTex reads information and code.
#         </doc>
#         <field name="mtex" type="NX_CHAR">
#             <doc>
#                  Absolute path to specific component of MTex source code.
#             </doc>
#         </field>
#         <field name="data" type="NX_CHAR">
#             <doc>
#                  Absolute path to specific component of MTex source code.
#             </doc>
#         </field>
#         <field name="cif" type="NX_CHAR">
#             <doc>
#                  Absolute path to specific component of MTex source code.
#             </doc>
#         </field>
#         <field name="ebsd" type="NX_CHAR">
#             <doc>
#                  Absolute path to specific component of MTex source code.
#             </doc>
#         </field>
#         <field name="pf" type="NX_CHAR">
#             <doc>
#                  Absolute path to specific component of MTex source code.
#             </doc>
#         </field>
#         <field name="odf" type="NX_CHAR">
#             <doc>
#                  Absolute path to specific component of MTex source code.
#             </doc>
#         </field>
#         <field name="tensor" type="NX_CHAR">
#             <doc>
#                  Absolute path to specific component of MTex source code.
#             </doc>
#         </field>
#         <field name="example" type="NX_CHAR">
#             <doc>
#                  Absolute path to specific component of MTex source code.
#             </doc>
#         </field>
#         <field name="import_wizard" type="NX_CHAR">
#             <doc>
#                  Absolute path to specific component of MTex source code.
#             </doc>
#         </field>
#         <field name="pf_extensions" type="NX_CHAR">
#             <doc>
#                  List of file type suffixes for which MTex assumes
#                  texture/pole figure information.
#             </doc>
#         </field>
#         <field name="ebsd_extensions" type="NX_CHAR">
#             <doc>
#                  List of file type suffixes for which MTex assumes EBSD content.
#             </doc>
#         </field>
#     </group>
#     <!--version as an instance of (NXprogram) one for MTex one for Matlab-->
# </definition>
