category: base
doc: |
  A base class to describe piezo settings for scanning probe microscopy.

  The Piezo-electric material of STM / STS gets deformed due to the applied electric field.
  Before using that piezo electric device the device needs to be configured like calibration 
  of the tips orientation or behavior due to the piezo electric materials deformation.
# Discussion: No need to create this base class rather we can define in spm application definition.
NXpiezo_config_spm(NXobject):
  piezo_material(NXpiezoelectric_material):
    doc: |
      The material description and properties of the piezoelectric scanner materials.
    curvature_radius_N(NX_NUMBER):
      unit: NX_LENGTH
      doc: |
        The N (substring) denotes X or Y. There are 2 parameters in X and Y directions. It can be set
        approximately to the length of the piezo tube.
  calibration(NXcalibration):
    calibration_type(NX_CHAR):
      doc: |
        The name of the calibration type, sometimes it is called 
        `active calibration`.
      enum: [active, passive]
      \@name: 
        doc: |
          A specific name of the calibration type (e.g. active type with name 'LHe').  
    calibrated_AXIS(NX_NUMBER):
      doc: |
        The AXIS (substring) denotes X, Y or Z. There are three directions X, Y, and Z for calibration, 
        along with three available controls: Calibration (m/V), Range (m), and HV gain each. Only
        two of these parameters are required to define the calibration. Consequently, when any
        value is changed, one of the other values will be automatically updated.
    hv_gain_N(NX_NUMBER):
      doc: |
        THe N (substring) denotes X or Y or Z. In some systems, there is an HV gain readout feature. For
        these systems, the HV gain should be automatically adjusted whenever the gain is
        changed at the high voltage amplifier.
    range_N(NX_NUMBER):
      doc: |
        The N (substring) denotes X or Y or Z. There are 3 parameters in X, Y and Z directions. The range
        is the maximum distance the piezo can move.
      unit: NX_LENGTH
    calibration_coeffecient_N(NX_NUMBER):
      doc: |
        The calibration coefficient is the ratio of the actual distance moved by the piezo to
        the voltage applied to the piezo. It is also called first-order correction.
      unit: NX_ANY
    tilt_N(NX_NUMBER):
      unit: NX_ANGLE
      doc: |
        The N (substring) denotes X and Y directions, and for both directions tilt needs to be adjusted according
        to the actual surface.
    2nd_order_corr_N(NX_NUMBER):
      doc: |
        The N (substring) denotes X and Y directions. If you know them, you can enter the 2nd order piezo 
        characteristics to compensate the error for that axis. 
        The following equation shows the 
        interpretation of the 2nd order correction parameters, For the X-piezo: 
            "Ux = 1/cx 路 X + cxx 路 X2" 
        with units:
            "[V] = [V/m] 路 [m] + [V/m2] 路 [m2]" 
        where cx is the calibration of the piezo X and cxx is the 2nd order correction. The unit for
        such the second-order correction is (V/m^2).
      unit: NX_ANY
    drift_N(NX_NUMBER):
      doc: |
        The N (substring) denotes X, Y and Z directions. Define the
        drift speed for all three axes. When the compensation is on, the piezo will start to
        move at that speed.
      unit: NX_VELOCITY