name: GH pages fairmat proposal

on:
  push:
    branches: [specific-nyaml-nxdl-compilation] # branch to trigger deployment

jobs:
  pages:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: install dependencies
      run: pip install -r requirements.txt
    - name: test
      run: make test
    - name: prepare
      run: make prepare
    - name: html
      run: make html
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        folder: build/manual/build/html
        branch: fairmat-docs
        clean: true