name: GH pages fairmat proposal

on:
  push:
    branches: [specific-nyaml-nxdl-compilation] # branch to trigger deployment

jobs:
  pages:
    runs-on: ubuntu-20.04
    steps:
    - name: install dependencies
      run: pip install -r requirements.txt
    - name: prepare
      run: make prepare
    - id: deployment
      uses: sphinx-notes/pages@v3
      with:
        publish: false
        documentation_path: ./manual/source
        requirements_path: ./requirements.txt
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ steps.deployment.outputs.artifact }}