name: GH pages fairmat proposal

on:
  push:
    branches: [fairmat]
  # pull_request:
  #   branches: [fairmat]

jobs:
  pages:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    - name: install dependencies
      run: pip install -r requirements.txt
    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v7
    - name: test
      run: make test
    - name: prepare
      run: make prepare
    - name: html
      run: make html
    - name: Deploy
      if: steps.branch-name.outputs.is_default == 'true'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/manual/build/html
        publish_branch: fairmat-docs
        destination_dir: docs
        force_orphan: true
    - name: Deploy PR
      if: steps.branch-name.outputs.is_default == 'false'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/manual/build/html
        publish_branch: fairmat-docs
        destination_dir: docs/${{ steps.branch-name.outputs.current_branch }}
        force_orphan: true


      